version: '3.8'
services:
  spa:
    container_name: eatsnow-premium
    build:
      context: ../eatsnow-spa
      dockerfile: Dockerfile
    volumes:
      - ../eatsnow-spa/src:/eatsnow-spa/src
      - ../eatsnow-spa/public:/eatsnow-spa/public
    ports:
      - 3000:3000
  php:
    container_name: eatsnow-app
    image: php:apache
    build:
      context: ../eatsnow-app
      dockerfile: Dockerfile
    volumes:
      - ../eatsnow-app:/var/www/html
    ports:
      - 8080:80
  php-db:
    container_name: eatsnow-app-db
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes:
      - "../eatsnow-app/db:/docker-entrypoint-initdb.d" 
    env_file:
      - ../eatsnow-app/.env
  rest-db:
    container_name: eatsnow-rest-db
    image: mysql:8.0
    ports:
      - 3308:3306
    env_file:
      - ../eatsnow-rest-service/.env
  rest:
    container_name: eatsnow-rest
    build:
      context: ../eatsnow-rest-service
      dockerfile: Dockerfile
    depends_on:
      - rest-db
    volumes:
      - ../eatsnow-rest-service/src:/eatsnow-rest/src
    env_file:
      - ../eatsnow-rest-service/.env
    stdin_open: true
    ports:
      - 8010:8010

  soap-db:
    container_name: eatsnow-soap-db
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=eatsnow-soap-service
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3309:3306
    volumes:
      - "../eatsnow-soap-service/eatsnowsoap/db:/docker-entrypoint-initdb.d" 

  soap:
    container_name: eatsnow-soap
    build:
      context: ../eatsnow-soap-service/eatsnowsoap
      dockerfile: dockerfile
    depends_on:
      - soap-db
    volumes:
      - ../eatsnow-soap-service/src:/app/src
    ports:
      - 8020:8020